### ISSUE TITLE
Failed to run JobManager

### ISSUE THREAD

**Issue by esyekas** [melentye/flink-kubernetes#4]
Hi,

When I start the Job manager, I am getting this error message. Note that I am running the Kubernetes locally in the minikube cluster.

```
2018-03-26 13:54:55,923 ERROR org.apache.flink.runtime.jobmanager.JobManager                - Failed to run JobManager.
java.lang.Exception: Could not create JobManager actor system

```
Attachment is the logs for your reference:
[logs-from-jobmanager-in-jobmanager-controller-rstcr.txt](https://github.com/melentye/flink-kubernetes/files/1848088/logs-from-jobmanager-in-jobmanager-controller-rstcr.txt)

**Comment by melentye** [comment]
job manager replication controller starts the pods which try to resolve the `jobmanager.flink.svc.cluster.local` domain name which is created by `jobmanager-service` (next step in the readme). I updated the readme to explain this better, hope it helps.
