### ISSUE TITLE
Send a job through CLI

### ISSUE THREAD

**Issue by jhagege** [melentye/flink-kubernetes#6]
Great README, thanks.
Any chance you are aware of a way to launch a job from CLI in my local machine, so that it runs in the Flink Cluster in Kubernetes?
Thanks.

**Comment by MichaelSteurer** [comment]
Hi @jhagege 
step-by-step guide for local and kube: https://github.com/ing-bank/flink-deployer

**Comment by melentye** [comment]
@jhagege the tool suggested by @MichaelSteurer looks very reasonable, perhaps give it a try.

**Comment by jhagege** [comment]
Thanks guys, will have a look at it :)
